language: ruby
sudo: false
branches:
  only:
  - source
rvm:
- 2.6.3
install:
- gem install --no-document bundler jekyll rake redcarpet
script:
- rake publish
env:
  global:
  - secure: D5zulESTpwuf8YVHy+IS0ajPY5krohQrGLmtvG12c7gvhgBX6fCOYD1VY7XLuG1TkJ+ngaXIcdN2gHbQDO9Pr2RCbJvRBNytx/QQmOQSZJGNmlbm1MHOtmheJWM7OtDupA+xCPljr+bQUfO2FUxPoXdDJxMcxw8XuT7+yj0ElFk=
