# Site settings
title: "Sgoettschkes.me"
description: "Personal blog and website by Sebastian Göttschkes, known as Sgoettschkes. Blogging about all things tech, mostly software engineering and DevOps."
url: "http://sgoettschkes.me"

# Build settings
exclude: ['contributions.pl', 'Rakefile', 'Vagrantfile']
timezone: Europe/Vienna
encoding: utf-8
permalink: /p/:title.html
markdown: redcarpet

# Serve settings
host: 0.0.0.0
port: 4000
