# Site settings
title: "Sgoettschkes.me - Coding 5 to 9"
description: "Personal blog and website by Sebastian Göttschkes, known as Sgoettschkes. Blogging about all things tech, mostly software engineering and DevOps."
url: "http://sgoettschkes.me"

# Build settings
timezone: Europe/Vienna
encoding: utf-8
markdown: kramdown
permalink: /p/:title.html
