name: Deploy
on: push

env:
  elixir-version: '1.13.4'
  erlang-version: '24.2.1'
  node-version: '18.0.0'

jobs:
  deploy-still:
    if: github.ref == 'refs/heads/still'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.erlang-version }}
          elixir-version: ${{ env.elixir-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - working-directory: ./priv/site/assets
        run: npm install
      - working-directory: ./priv/site/assets
        run: npx tailwindcss --input=css/app.css --output=../css/app.css --postcss
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix publish
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MIX_ENV: 'prod'

  deploy-jekyll:
    if: github.ref == 'refs/heads/source'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: source
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - run: gem install --no-document bundler jekyll rake
      - run: rake publish
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
