name: Deploy
on: push

jobs:
  deploy:
    if: github.ref == 'refs/heads/source'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: source
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.3
      - run: gem install --no-document bundler jekyll rake
      - run: rake publish
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
