name: Deploy
on: push

env:
  elixir-version: '1.14.5'
  erlang-version: '26.2'
  node-version: '18.18.0'

jobs:
  deploy-still:
    if: github.ref == 'refs/heads/still'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.erlang-version }}
          elixir-version: ${{ env.elixir-version }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.node-version }}
      - working-directory: ./priv/site/assets
        run: yarn install
      - working-directory: ./priv/site/assets
        run: npx tailwindcss --input=css/app.css --output=../css/app.css --postcss
      - run: mix deps.get
      - run: mix format --check-formatted
      - run: mix publish
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          MIX_ENV: 'prod'
